### ISSUE TITLE
Text display bug in compose view

### ISSUE THREAD

**Issue by yufansun** [psturmfels/ios-team#23]
Sometimes my input text doesn't show up on the compose view screen. This bug happened in my and Sindy's phones during test. Still trying to figure out when this bug happens and how to solve it.

![img3](https://cloud.githubusercontent.com/assets/15572885/19530211/eb3880f0-9600-11e6-8a09-3faa3b6d5d2b.jpeg)

**Comment by psturmfels** [comment]
Hm I see the screenshot, but I can't seem to replicate this problem on any of my hardware simulators, nor can I replicate it on my phone. Let me dig through the code and see if anything obvious jumps out at me.

**Comment by psturmfels** [comment]
I took a stab at solving this problem with a2e61f7f1f578ef25d315f691fc2a10766676d11, although I have no idea whether the solution actually worked.
Could you try testing what you did again and seeing whether the problem still occurs as of the latest push?

**Comment by yufansun** [comment]
This doesn't work.
But I realized this bug happen in my phone when I change my keyboard. (eg. if I change from English keyboard to Emoji and change back to English, the placeholder and UITextfield both disappears)

**Comment by psturmfels** [comment]
Dang. Hmm I still can't seem to replicate this bug. You'll have to show me in person.

**Comment by qinyeli** [comment]
The errors occurs only in Yufan and my phone because we have multiple language keyboard.
Every time we switch language, `keyboardWillShow` is called, but `keyboardWillHide` is not. As a result, the following line is run for multiple times.

```
self.composeTextView.frame.size.height -= keyboardFrame.height
```

It is confusing though as I switch between 4 language keyboards, sometimes `keyboardWillShow` is not called, sometimes called once, sometimes twice. Basic observations are
- Switching between Chinese and Japanese: once
- Switching between Japanese and {English, French, emoji}: once
- Switching between Chinese and {English, French, emoji}: twice
- Switching between English, French and emoji: not called

Given the complexity, I would say simply rewriting the code as

```
self.composeTextView.frame.size.height = SOME_CONSTANT - keyboardFrame.height
```

is the easiest way to fix the bug.

**Comment by yufansun** [comment]
Yes, you are right.
I fixed the bug on my phone simply by changing 
`self.composeTextView.frame.size.height -= keyboardFrame.height` 
in `keyboardWillShow` function to 
`self.composeTextView.frame.size.height = keyboardFrame.height`

**Comment by psturmfels** [comment]
Does this fix work? Can we close this issue/Can you push the solution?

**Comment by yufansun** [comment]
The bug is fixed.
I cannot push to master directly, so created a new branch and pushed my changes there: a2e61f7f1f578ef25d315f691fc2a10766676d11
