### ISSUE TITLE
App currently does not save messages across closing

### ISSUE THREAD

**Issue by psturmfels** [psturmfels/ios-team#7]
Currently, if you close the app and then open it again, you'll notice that all of the messages from the previous session have been erased. We need the app to be able to remember things after it has been closed. This is called "Persistent Storage" or "Persist Data" in swift terms. Look this up and figure out how to save messages after the app has been closed.

**Comment by qinyeli** [comment]
It turns out that saving data using `NSKeyedArchiver.archiveRootObject` would overwrite the previous data. My understanding is that this means the data should b saved as an array rather than separate object. But the problems is, while we have an array of RoarMessage in the current data structure, we do not have an array RoarMessageCore.

If this was in C++, I would store RoarMessageCore in an array, and make RoarMessage points to the corresponding RoarMessageCore, but I am not sure whether it is good practice in Swift. Another method I could think of now, is to have a separate array of RoarMessageCore, but that seems to be unnecessarily doubling the memory size.

I will check if there are ways to get around this.

**Comment by psturmfels** [comment]
Hey Qinye,
Is it not possible to just create an array of type RoarMessageCore from cellDataArray
when you need to save the data? 

If you can't find another solution to this problem, I'll change the RoarTableView class to store an array
of type RoarMessageCore instead of type RoarMessage, so that your above approach will work.

**Comment by qinyeli** [comment]
I guess I can, but every time the user add a message, I need to call the store function.
Does that mean I would be converting an array to another array every time a message is added?

I am not very sure how `NSKeyedArchiver.archiveRootObject` works. Might check that tomorrow.

**Comment by psturmfels** [comment]
Close with updates to core_data branch
